### ISSUE TITLE
Exception in thread "main" java.lang.ArithmeticException: / by zero

### ISSUE THREAD

**Issue by brianpenghe** [aboyle/F-seq#10]
I ran into this error message multiple times. The message is:

Exception in thread "main" java.lang.ArithmeticException: / by zero
        at edu.duke.igsp.gkde.KDEChromosome.run(KDEChromosome.java:325)
        at edu.duke.igsp.gkde.Main.main(Main.java:272)

Any ideas?

**Comment by am33567** [comment]
Hi, I got the same error message, did you figure out what was the problem?

Thanks!

**Comment by brianpenghe** [comment]
YES .  It turned out that Fseq is not good at handling mini chromosomes, which explain why it has more errors for hg38 data. What you could do is to remove the mini chromosomes in your fasta genome file, then build index, map and peakcall.

**Comment by aboyle** [comment]
These errors are from the estimation of fragment length which we thought was fixed but apparently not. An easy work-around is to provide a fragment length either based on what you cut from your gel or from the estimates from a larger chromosome.
