### ISSUE TITLE
version 1.84 result not consistent for the same data

### ISSUE THREAD

**Issue by onceupon** [aboyle/F-seq#11]
i ran fseq on the same file twice, with the same default setting,
however, the calculate threshold and the number of peaks found are different
seems that i might have to set the wg threshold, 
want to know more about the wg threshold, thanks

--->first run
$ fseq -v -of bed 22.bed
F-Seq Version 1.84
Settings: 
	window=2860
	bandwidth=100
	**threshold = 1.5770507**
	est. fragment size = 99
	sequence length = 36
chr22: first=16050351, last=51239680
....................
.....................
chr22: Completed in 6.471 seconds.
chr22: Found** 5118** peaks.

--->second run
$fseq -v -of bed 22.bed
F-Seq Version 1.84
Settings: 
	window=2860
	bandwidth=100
	**threshold = 1.5880933**
	est. fragment size = 99
	sequence length = 36
chr22: first=16050351, last=51239680
....................
.....................
chr22: Completed in 6.324 seconds.
chr22: Found **5058** peaks.

**Comment by aboyle** [comment]
There is a bit of randomness in the threshold estimation of F-seq as well as the fragment size estimation because of the sub-sampling. Setting the threshold will make the behavior of the program consistent.

**Comment by aboyle** [comment]
That would entirely depend on what you are doing. The default is 4 standard deviations but something higher than that would be more appropriate. -wg or -t would work
