### ISSUE TITLE
mapviewToBed.pl: missing declare line 60 for $strand

### ISSUE THREAD

**Issue by splaisan** [aboyle/F-seq#4]
(in version May 20, 2008) downloaded as zip
my $start;
    my $end;
    add ===> my $strand;
    if($strand eq "+") {
        $start = $toprint[2];
        $end = $toprint[2] + $offset;
    } elsif($strand eq "-") {
        $end = $toprint[2];
        $start = $toprint[2] - $offset;
    }

**Comment by aboyle** [comment]
This is not in the current version.
